{{- if .Values.certificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "pds.fullname" . }}-tls
  {{- if and .Values.certificate.metadata .Values.certificate.metadata.namespace }}
  namespace: {{ .Values.certificate.metadata.namespace }}
  {{- else }}
  namespace: {{ include "pds.ns" . }}
  {{- end }}
  labels:
    {{- include "pds.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replication-allowed: "true"
      replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
    {{- if .Values.certificate.secretTemplate }}
    {{- with .Values.certificate.secretTemplate.annotations }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.certificate.secretTemplate.labels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  issuerRef:
    {{- toYaml .Values.certificate.issuerRef | nindent 4 }}
  subject:
    {{- toYaml .Values.certificate.subject | nindent 4 }}
  commonName: {{ .Values.config.hostname | quote }}
  dnsNames:
    - {{ .Values.config.hostname | quote }}
    - {{ printf "*.%s" .Values.config.hostname | quote }}
  isCA: false
  usages:
    - server auth
  {{- with .Values.certificate }}
  {{- with .ipAddresses }}
  ipAddresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .uris }}
  uris:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .emailAddresses }}
  emailAddresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .nameConstraints }}
  nameConstraints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .duration }}
  duration: {{ . }}{{ end }}
  {{- with .renewBefore }}
  renewBefore: {{ . }}{{ end }}
  {{- with .renewBeforePercentage }}
  renewBeforePercentage: {{ . }}{{ end }}
  {{- with .literalSubject }}
  literalSubject: {{ . }}{{- end }}
  {{- with .revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}{{- end }}
  {{- with .encodeUsagesInRequest }}
  encodeUsagesInRequest: {{ . }}{{- end }}
  {{- with .additionalOutputFormats }}
  additionalOutputFormats:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- end }}
{{- end }}
