on:
  push:
    branches:
      - main
name: publish

env:
  COMPOSE_DOCKER_CLI_BUILD: '1'
  DOCKER_BUILDKIT: '1'
  DOCKER_USRNAME: harrybrwn

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install yq
      env:
        VERSION: v4.44.5
        BINARY: yq_linux_amd64
      run: |
        wget "https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz" -O - |\
          tar xz && mv ${BINARY} /usr/local/bin/yq && chmod +x /usr/local/bin/yq
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        platforms: linux/amd64,linux/arm/v7
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get @atproto/pds version
      id: pds
      run: |
        echo "version=$(yq -r '.importers.".".dependencies."@atproto/pds".version' pnpm-lock.yaml)" >> "$GITHUB_OUTPUT"
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        # push: true
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.DOCKER_USERNAME }}/pds:latest
          ${{ env.DOCKER_USERNAME }}/pds:${{ steps.pds.outputs.version }}
          ${{ env.DOCKER_USERNAME }}/pds:${{ github.sha }}
